var PROGRESS_BAR_SIZE = {
    SMALL: 0,
    MEDIUM: 1,
    LARGE: 2
}
var PROGRESS_BAR_TYPE = {
    MP: 0,
    HP: 1
}
var PROGRESS_BAR_TEXT_POSITION = {
    UNDER_LEFT: 0,
    UNDER_RIGHT: 1,
    UNDER_CENTER: 2,
    OVER_LEFT: 3,
    OVER_RIGHT: 4,
    OVER_CENTER: 5,
    ON: 6,
    NO_TEXT: 7
}